from .crawler import Crawler
from .crawlerAnimesGratis import CrawlerAnimesGratis
from .crawlerAnimesOnline import CrawlerAnimesOnline
from .crawlerGoyabu import CrawlerGoyabu
from .crawlerGoyabuOld import CrawlerGoyabuOld
from .crawlerBakashiTvOld import CrawlerBakashiTvOld
from .crawlerBakashiTv import CrawlerBakashiTv
from .crawlerAssistirAnimes import CrawlerAssistirAnimes
from .crawlerAnimesHouse import CrawlerAnimesHouse
