from .crawler import Crawler
from .crawlerAnimesHouseAndAnimesGratis import CrawlerAnimesHouseAndAnimesGratis
from .crawlerAnimesOnline import CrawlerAnimesOnline
from .crawlerGoyabu import CrawlerGoyabu
from .crawlerGoyabuOld import CrawlerGoyabuOld
from .crawlerBakashiTvOld import CrawlerBakashiTvOld